# assignment 1
# week 1 
# day 2  
#calculator


import math
decoration = "*****************************"
start_message = str .upper("calculator is starting" )
print (decoration)
print (f"    {start_message}")
print (decoration)


print ("|-----------------------------|")
print ("|         calculator          |")
print ("|-----------------------------|")
print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
print ("|-----------------------------|")
print ("|                             |")
print ("|-----------------------------|")
print ("|  1    |     2    |     3    |")
print ("|-----------------------------|")
print ("|  4    |     5    |     6    |")
print ("|-----------------------------|")
print ("|  7    |     8    |     9    |")
print ("|-----------------------------|")
print ("|                             |")
print ("|  + |  - | * | / | sqrt | sq |")
print ("|                             |")
print ("|-----------------------------|")


print (decoration)
number_1 = float(input ("ENTER THE FIRST NO. TO BEGIN CALCULATION: "))
print (decoration)


def output_dis (number_1):
    print ("|                             |")
print ("|-----------------------------|")
print ("|         calculator          |")
print ("|-----------------------------|")
print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
print ("|-----------------------------|")
print (f"|= {number_1}                       |")
print ("|-----------------------------|")
print ("|  1    |     2    |     3    |")
print ("|-----------------------------|")
print ("|  4    |     5    |     6    |")
print ("|-----------------------------|")
print ("|  7    |     8    |     9    |")
print ("|-----------------------------|")
print ("|                             |")
print ("|  + |  - | * | / | sqrt | sq |")
print ("|                             |")
print ("|-----------------------------|")

print (decoration)
print ("SELECT ANY OPERATION FROM THE LIST BELOW TO COMPLETE THE CALCULATION: ")
operation = str(input("+ , - , * , / , sqrt , sq ::: "))
def output_dis_operand(operation):
     print ("|                             |")
print ("|-----------------------------|")
print ("|         calculator          |")
print ("|-----------------------------|")
print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
print ("|-----------------------------|")
print (f"|= {number_1} {operation}                 |")
print ("|-----------------------------|")
print ("|  1    |     2    |     3    |")
print ("|-----------------------------|")
print ("|  4    |     5    |     6    |")
print ("|-----------------------------|")
print ("|  7    |     8    |     9    |")
print ("|-----------------------------|")
print ("|  1    |     2    |     3    |")
print ("|-----------------------------|")
print ("|  4    |     5    |     6    |")
print ("|-----------------------------|")
print ("|  7    |     8    |     9    |")
print ("|-----------------------------|")
print ("|                             |")
print ("|  + |  - | * | / | sqrt | sq |")
print ("|                             |")
print ("|-----------------------------|")

output_dis_message_banner = "ANSWER FOR YOUR QUESTION IS AS FOLLOWS"
print (decoration)
print(decoration)
print (output_dis_message_banner)
print (decoration)
print(decoration)


if operation == "sqrt":
    total = (math.sqrt(number_1))
    print ("|                             |")
    print ("|-----------------------------|")
    print ("|         calculator          |")
    print ("|-----------------------------|")
    print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
    print ("|-----------------------------|")
    print (f"|= {number_1} {operation} = {total}              |")
    print ("|-----------------------------|")
    print ("|  1    |     2    |     3    |")
    print ("|-----------------------------|")
    print ("|-----------------------------|")
    print ("|  4    |     5    |     6    |")
    print ("|-----------------------------|")
    print ("|  7    |     8    |     9    |")
    print ("|-----------------------------|")
    print ("|                             |")
    print ("|  + |  - | * | / | sqrt | sq |")
    print ("|                             |")
    print ("|-----------------------------|")
    

elif  operation == "sq":
   total = str((number_1) * (number_1))
   print ("|                             |")
   print ("|-----------------------------|")
   print ("|         calculator          |")
   print ("|-----------------------------|")
   print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
   print ("|-----------------------------|")
   print (f"|= {number_1} {operation} = {total}              |")
   print ("|-----------------------------|")
   print ("|  1    |     2    |     3    |")
   print ("|-----------------------------|")
   print ("|-----------------------------|")
   print ("|  4    |     5    |     6    |")
   print ("|-----------------------------|")
   print ("|  7    |     8    |     9    |")
   print ("|-----------------------------|")
   print ("|                             |")
   print ("|  + |  - | * | / | sqrt | sq |")
   print ("|                             |")
   print ("|-----------------------------|")

elif  operation == "+":
    print(decoration)
    number_2 = float(input("ENTER SECOND NO. TO COMPLETE THE CALCULATION: "))
    total = str(number_1 + number_2)
    print ("|                             |")
    print ("|-----------------------------|")
    print ("|         calculator          |")
    print ("|-----------------------------|")
    print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
    print ("|-----------------------------|")
    print (f"|= {number_1} {operation} {number_2} = {total}    |")
    print ("|-----------------------------|")
    print ("|  1    |     2    |     3    |")
    print ("|-----------------------------|")
    print ("|-----------------------------|")
    print ("|  4    |     5    |     6    |")
    print ("|-----------------------------|")
    print ("|  7    |     8    |     9    |")
    print ("|-----------------------------|")
    print ("|                             |")
    print ("|  + |  - | * | / | sqrt | sq |")
    print ("|                             |")
    print ("|-----------------------------|")
        
elif  operation == "-":
    print(decoration)
    number_2 = float(input("ENTER SECOND NO. TO COMPLETE THE CALCULATION: "))
    total = str(number_1 - number_2)
    print ("|                             |")
    print ("|-----------------------------|")
    print ("|         calculator          |")
    print ("|-----------------------------|")
    print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
    print ("|-----------------------------|")
    print (f"|= {number_1} {operation} {number_2} = {total}    ")
    print ("|-----------------------------|")
    print ("|  1    |     2    |     3    |")
    print ("|-----------------------------|")
    print ("|-----------------------------|")
    print ("|  4    |     5    |     6    |")
    print ("|-----------------------------|")
    print ("|  7    |     8    |     9    |")
    print ("|-----------------------------|")
    print ("|                             |")
    print ("|  + |  - | * | / | sqrt | sq |")
    print ("|                             |")
    print ("|-----------------------------|")


elif  operation == "*":
    print(decoration)
    number_2 = float(input("ENTER SECOND NO. TO COMPLETE THE CALCULATION: "))
    total = str(number_1 * number_2)
    print ("|                             |")
    print ("|-----------------------------|")
    print ("|         calculator          |")
    print ("|-----------------------------|")
    print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
    print ("|-----------------------------|")
    print (f"|= {number_1} {operation} {number_2} = {total}    ")
    print ("|-----------------------------|")
    print ("|  1    |     2    |     3    |")
    print ("|-----------------------------|")
    print ("|-----------------------------|")
    print ("|  4    |     5    |     6    |")
    print ("|-----------------------------|")
    print ("|  7    |     8    |     9    |")
    print ("|-----------------------------|")
    print ("|                             |")
    print ("|  + |  - | * | / | sqrt | sq |")
    print ("|                             |")
    print ("|-----------------------------|")


elif operation == "/":
    print(decoration)
    number_2 = float(input("ENTER SECOND NO. TO COMPLETE THE CALCULATION: "))
    total = str(number_1 / number_2)
    print ("|                             |")
    print ("|-----------------------------|")
    print ("|         calculator          |")
    print ("|-----------------------------|")
    print ("|1 2 3 4 5 6 7 8 9 0 1 2 3 4 5|")
    print ("|-----------------------------|")
    print (f"|= {number_1} {operation} {number_2} = {total}    ")
    print ("|-----------------------------|")
    print ("|  1    |     2    |     3    |")
    print ("|-----------------------------|")
    print ("|-----------------------------|")
    print ("|  4    |     5    |     6    |")
    print ("|-----------------------------|")
    print ("|  7    |     8    |     9    |")
    print ("|-----------------------------|")
    print ("|                             |")
    print ("|  + |  - | * | / | sqrt | sq |")
    print ("|                             |")
    print ("|-----------------------------|")

print(decoration)
end_greetings = str.upper("thank you for using calculator ")
print (end_greetings)